prompt Importing table USER_TAB_COLUMNS...
set feedback off
set define off
insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKDATE', 'INIT_DATE', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKDATE', 'SERIAL_NO', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKDATE', 'TABLENAME', 'VARCHAR2(18)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKDATE', 'ENTRUST_DATE', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKDATE', 'FUND_DATE_BACK', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKDATE', 'STOCK_DATE_BACK', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'INIT_DATE', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'SERIAL_NO', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'TABLENAME', 'VARCHAR2(18)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'BUSINESS_TYPE', 'CHAR(1)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'BUSINESS_FLAG', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'REMARK', 'VARCHAR2(2000)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'FILE_KIND', 'CHAR(1)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'FILE_TYPE', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'EXCHANGE_TYPE', 'VARCHAR2(4)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'STOCK_CODE', 'VARCHAR2(6)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'FROZEN_CODE', 'VARCHAR2(6)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'STOCK_TYPE', 'VARCHAR2(4)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'STOCK_NAME', 'VARCHAR2(32)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'ENTRUST_BS', 'CHAR(1)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKENTRUST', 'ENTRUST_WAY', 'CHAR(1)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'INIT_DATE', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'SERIAL_NO', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'TABLENAME', 'VARCHAR2(18)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'FARE_KIND_STR', 'VARCHAR2(255)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'FARE_KIND', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'STANDARD_FARE0', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'EXCHANGE_FARE0', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'EXCHANGE_FARE1', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'EXCHANGE_FARE2', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'EXCHANGE_FARE3', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'EXCHANGE_FARE4', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'EXCHANGE_FARE5', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'EXCHANGE_FARE6', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'EXCHANGE_FAREX', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKEXCHANGEFARE', 'EXCHANGE_FARE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFARE', 'INIT_DATE', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFARE', 'SERIAL_NO', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFARE', 'TABLENAME', 'VARCHAR2(18)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFARE', 'FARE_KIND_STR', 'VARCHAR2(255)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFARE', 'FARE_KIND', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFARE', 'FARE0', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFARE', 'FARE1', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFARE', 'FARE2', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFARE', 'FARE3', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFARE', 'FAREX', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFARE', 'FARE_REMARK', 'VARCHAR2(2000)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFARE', 'ROOM_CODE', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFARE', 'SEAT_NO', 'VARCHAR2(8)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'INIT_DATE', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'SERIAL_NO', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'TABLENAME', 'VARCHAR2(18)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'OCCUR_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'FROZEN_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'UNFROZEN_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'CORRECT_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'REAL_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'CLEAR_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'FROZEN_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'UNFROZEN_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'CORRECT_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'REAL_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'POST_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFS', 'POST_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFSEX', 'INIT_DATE', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFSEX', 'SERIAL_NO', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFSEX', 'TABLENAME', 'VARCHAR2(18)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFSEX', 'MARKET_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFSEX', 'ENABLE_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFSEX', 'REAL_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFSEX', 'MARKET_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFSEX', 'ENABLE_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFSEX', 'REAL_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFSEX', 'POST_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKFSEX', 'POST_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKMATCH', 'INIT_DATE', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKMATCH', 'SERIAL_NO', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKMATCH', 'TABLENAME', 'VARCHAR2(18)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKMATCH', 'MATCH_STATUS', 'CHAR(1)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKMATCH', 'ENTRUST_NO', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKMATCH', 'BUSINESS_NO', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKMATCH', 'BUSINESS_ID', 'VARCHAR2(32)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKMATCH', 'REPORT_NO', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKMATCH', 'ORDER_ID', 'VARCHAR2(10)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKMATCH', 'BUSINESS_PRICE', 'NUMBER(22,3)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKMATCH', 'BUSINESS_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKMATCH', 'BUSINESS_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'INIT_DATE', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'SERIAL_NO', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'TABLENAME', 'VARCHAR2(18)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'REBATE_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'BROKERAGE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'ENTRUST_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'UNCOME_BUY_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'UNCOME_SELL_AMOUNT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'UNCOME_BUY_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'UNCOME_SELL_BALANCE', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'STOCK_INTEREST', 'NUMBER(22,8)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'STOCK_INTERESTX', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'PROFIT', 'NUMBER(22,2)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'SET_SEAT_NO', 'VARCHAR2(8)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKOTHER', 'REAL_STATUS', 'CHAR(1)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKUSER', 'INIT_DATE', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKUSER', 'SERIAL_NO', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKUSER', 'TABLENAME', 'VARCHAR2(18)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKUSER', 'BRANCH_NO', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKUSER', 'FUND_ACCOUNT', 'VARCHAR2(18)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKUSER', 'EXCHANGE_TYPE', 'VARCHAR2(4)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKUSER', 'STOCK_ACCOUNT', 'VARCHAR2(20)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKUSER', 'REPORT_ACCOUNT', 'VARCHAR2(20)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKUSER', 'MONEY_TYPE', 'VARCHAR2(3)', ''' ''', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKUSER', 'DEFAULT_BRANCH', 'NUMBER(22,0)', '0', 'NOT NULL');

insert into USER_TAB_COLUMNS ('HS_SETT', TABLE_NAME, COLUMN_NAME, CASEA.DATA_TYPEWHEN'NUMBER'THE, CASEA.DATA_TYPEWHEN'NUMBER'THE, 'NOTNULL')
values ('HS_SETT', 'TCHECKUSER', 'DEFAULT_ACCOUNT', 'VARCHAR2(18)', ''' ''', 'NOT NULL');

prompt Done.
